### ISSUE TITLE
Image Blobs

### ISSUE THREAD

**Issue by TheCodeTraveler** [brminnick/LambdaTriggersSample#1]
![LambdaTriggersSample](https://user-images.githubusercontent.com/13558917/214357391-7719ca74-2b37-4e46-ac4d-50570011a790.png)

**Comment by brminnick** [comment]
![LambdaTriggersSample](https://user-images.githubusercontent.com/13558917/214541304-fde8ed80-b5f9-49ba-9038-b743f485a420.png)

**Comment by brminnick** [comment]
<img width="945" alt="LambdaTriggersSample" src="https://user-images.githubusercontent.com/13558917/214541434-0244c7f0-cc13-4273-89b0-af5ffd9f9786.png">
